language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
 - export REPO=`pwd`
install:
  - sudo apt-get update
  - sudo apt-get install -qq python-yaml python-dateutil
  - sudo apt-get install -qq python3-yaml python3-dateutil
  - sudo apt-get install -qq git mercurial bzr subversion
  - echo $PYTHONPATH
  - python -c 'import sys;print(sys.path)'
  - python setup.py install
  - hg --version
  - bzr --version
  - git --version
  - svn --version
# Set git config to silence some stuff in the tests
  - git config --global user.email "foo@example.com"
  - git config --global user.name "Foo Bar"
# Set the hg user
  - echo -e "[ui]\nusername = Your Name <your@mail.com>" >> ~/.hgrc
# Set the bzr user
  - bzr whoami "Your Name <name@example.com>"
# command to run tests
script:
  - python -m nose --with-coverage --cover-package vcstools test
notifications:
  email: false
