language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - sudo apt-get update -qq
  - python setup.py build
  - sudo pip install pyyaml
  - sudo apt-get install -qq git mercurial subversion
# command to run tests
script:
  - which python
  - /usr/bin/env python --version
  - nosetests --with-coverage --cover-package vcstools
notifications:
  email: false
