language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - python setup.py build
  - sudo pip install pyyaml
  - sudo pip install coverage
  - sudo pip install python-dateutil
# Set git config to silence some stuff in the tests
  - git config --global user.email "foo@example.com"
  - git config --global user.name "Foo Bar"
# Set the hg user
  - echo -e "[ui]\nusername = Your Name <your@mail.com>" >> ~/.hgrc
# Set the bzr user
  - bzr whoami "Your Name <name@example.com>"
# command to run tests
script:
  - nosetests --with-coverage --cover-package vcstools
notifications:
  email: false
